### ISSUE TITLE
Changements Quality Of Life

### ISSUE THREAD

**Issue by Zuruuh** [Blagues-API/blagues-api.fr#54]
Actuellement c'est assez relou de gérer le projet en local quand on veux bosser dessus sans docker, ducoup je  propose quelques changements "quality of life"

- Ajout d'un fichier .nvmrc:
  Certains contrib ont des soucis en lien avec leur version de node en lancant le projet et le moyen le plus simple de le fix est de revert sa version de node sur la lts (v16.15.1)
- Autocomplétion pour la config nuxt:
  Pas forcément utile vu que c'est pas qlq chose qu'on modifie souvent mais c'est cool a avoir pour le type checking
- Un peu anecdotique mais préciser quelque part (dans le readme par exemple) qu'en local il faut bien aller sur son localhost et pas sur l'ip que renvoie nuxt avec le dev server, sinon ça peux empêcher certaines feature de l'objet window de s'activer (window.crypto.subtle notamment, qui fais crash l'auth avec discord)

**Comment by DraftProducts** [comment]
C'est bon pour moi même si l'objectif est de passer à Nuxt3 qui est full TS, j'aimerais juste attendre la sortie officielle (et la doc complète de migration).
